language: java
jdk:
- oraclejdk9
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
branches:
  only:
  - master
  - dev
#deploy:
#  provider: heroku
#  api_key:
#    secure: "API KEY"
